;
;	This file was generated by the GEOS Resource Compiler
;
;	DO NOT EDIT! Any changes will be lost!
;
;	Edit proper resource file instead.
;

		.segment "DIRENTRY"

	.byte 131
	.word 0
	.byte "123456789 123456"
	.word 0
	.byte 0
	.byte 6
	.byte 22, 7, 14, 23, 42

	.word 0
	.byte "PRG formatted GEOS file V1.0"

		.segment "FILEINFO"

	.import __VLIR0_START__, __STARTUP_RUN__

	.byte 3, 21, 63 | $80
	.byte %11111111, %11111111, %11111111
	.byte %10000000, %00000000, %00000001
	.byte %10000000, %00000000, %00000001
	.byte %10000000, %00000000, %00000001
	.byte %10000000, %00000000, %00000001
	.byte %10000000, %00000000, %00000001
	.byte %10000000, %00000000, %00000001
	.byte %10000000, %00000000, %00000001
	.byte %10000000, %00000000, %00000001
	.byte %10000000, %00000000, %00000001
	.byte %10000000, %00000000, %00000001
	.byte %10000000, %00000000, %00000001
	.byte %10000000, %00000000, %00000001
	.byte %10000000, %00000000, %00000001
	.byte %10000000, %00000000, %00000001
	.byte %10000000, %00000000, %00000001
	.byte %10000000, %00000000, %00000001
	.byte %10000000, %00000000, %00000001
	.byte %10000000, %00000000, %00000001
	.byte %10000000, %00000000, %00000001
	.byte %11111111, %11111111, %11111111
	.byte 131, 6, 0
	.word __VLIR0_START__, __VLIR0_START__ - 1, __STARTUP_RUN__

	.byte "Class Name"
	.res  (12 - 10), $20
	.byte "V1.0"
	.byte 0, 0, 0
	.byte 128

	.byte "Maciej Witkowiak"
	.byte 0
	.res  (63 - 17)

	.byte "Information text"
	.byte 0

