;
;	This file was generated by the GEOS Resource Compiler
;
;	DO NOT EDIT! Any changes will be lost!
;
;	Edit proper resource file instead.
;

		.segment "DIRENTRY"

	.byte 131
	.word 0
	.byte "test"
	.res  (16 - 4), $a0
	.word 0
	.byte 1
	.byte 6
	.byte 22, 7, 14, 23, 42

	.word 0
	.byte "PRG formatted GEOS file V1.0"

		.segment "FILEINFO"

	.import __VLIR0_START__, __STARTUP_RUN__

	.byte 3, 21, 63 | $80
	.byte %11111111, %11111111, %11111111
	.byte %10000000, %00000000, %00000001
	.byte %10000000, %00000000, %00000001
	.byte %10000000, %00000000, %00000001
	.byte %10000000, %00000000, %00000001
	.byte %10000000, %00000000, %00000001
	.byte %10000000, %00000000, %00000001
	.byte %10000000, %00000000, %00000001
	.byte %10000000, %00000000, %00000001
	.byte %10000000, %00000000, %00000001
	.byte %10000000, %00000000, %00000001
	.byte %10000000, %00000000, %00000001
	.byte %10000000, %00000000, %00000001
	.byte %10000000, %00000000, %00000001
	.byte %10000000, %00000000, %00000001
	.byte %10000000, %00000000, %00000001
	.byte %10000000, %00000000, %00000001
	.byte %10000000, %00000000, %00000001
	.byte %10000000, %00000000, %00000001
	.byte %10000000, %00000000, %00000001
	.byte %11111111, %11111111, %11111111
	.byte 131, 6, 1
	.word __VLIR0_START__, __VLIR0_START__ - 1, __STARTUP_RUN__

	.byte "TestApp"
	.res  (12 - 7), $20
	.byte "V1.0"
	.byte 0, 0, 0
	.byte 0

	.byte "Maciej Witkowiak"
	.byte 0
	.res  (63 - 17)

	.byte "This is just an example."
	.byte 0

		.segment "RECORDS"

	.import __VLIR0_START__, __VLIR0_LAST__, __BSS_SIZE__
	.import __VLIR1_START__, __VLIR1_LAST__
	.import __VLIR2_START__, __VLIR2_LAST__

	.byte .lobyte ((__VLIR0_LAST__ - __VLIR0_START__ - __BSS_SIZE__ - 1) /    254) + 1
	.byte .lobyte ((__VLIR0_LAST__ - __VLIR0_START__ - __BSS_SIZE__ - 1) .MOD 254) + 2
	.byte .lobyte ((__VLIR1_LAST__ - __VLIR1_START__ - 1) /    254) + 1
	.byte .lobyte ((__VLIR1_LAST__ - __VLIR1_START__ - 1) .MOD 254) + 2
	.byte .lobyte ((__VLIR2_LAST__ - __VLIR2_START__ - 1) /    254) + 1
	.byte .lobyte ((__VLIR2_LAST__ - __VLIR2_START__ - 1) .MOD 254) + 2

	.export __STACKSIZE__ : absolute = $0000

	.export __OVERLAYSIZE__ : absolute = $1000

