;
; File generated by cc65 v 2.19 - Git e95db437a
;
	.fopt		compiler,"cc65 v 2.19 - Git e95db437a"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	on
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.dbg		file, "checkversion.c", 1548, 1657744212
	.dbg		file, "/cygdrive/c/Users/Craig Vella/Documents/GitHub/cc65/include/stdio.h", 6901, 1657744211
	.dbg		file, "/cygdrive/c/Users/Craig Vella/Documents/GitHub/cc65/include/stdlib.h", 6145, 1657744211
	.forceimport	__STARTUP__
	.dbg		sym, "printf", "00", extern, "_printf"
	.import		_printf
	.export		_main

.segment	"RODATA"

S0004:
	.byte	$A4,$A4,$C3,$C3,$36,$35,$A4,$A4,$20,$49,$53,$20,$49,$4E,$43,$4F
	.byte	$52,$52,$45,$43,$54,$4C,$59,$20,$44,$45,$46,$49,$4E,$45,$44,$20
	.byte	$41,$53,$20,$28,$D6,$C5,$D2,$A4,$CD,$C1,$CA,$CF,$D2,$20,$2A,$20
	.byte	$30,$58,$31,$30,$30,$29,$20,$2B,$20,$28,$D6,$C5,$D2,$A4,$CD,$C9
	.byte	$CE,$CF,$D2,$20,$2A,$20,$30,$58,$31,$30,$29,$0D,$00
S0003:
	.byte	$A4,$A4,$C3,$C3,$36,$35,$A4,$A4,$20,$49,$53,$20,$44,$45,$46,$49
	.byte	$4E,$45,$44,$20,$43,$4F,$52,$52,$45,$43,$54,$4C,$59,$20,$41,$53
	.byte	$20,$28,$D6,$C5,$D2,$A4,$CD,$C1,$CA,$CF,$D2,$20,$2A,$20,$30,$58
	.byte	$31,$30,$30,$29,$20,$2B,$20,$D6,$C5,$D2,$A4,$CD,$C9,$CE,$CF,$D2
	.byte	$0D,$00
S0002:
	.byte	$43,$4F,$4D,$50,$49,$4C,$45,$52,$20,$56,$45,$52,$53,$49,$4F,$4E
	.byte	$20,$49,$53,$20,$25,$55,$2E,$25,$55,$0D,$00
S0001:
	.byte	$A4,$A4,$C3,$C3,$36,$35,$A4,$A4,$20,$44,$45,$46,$49,$4E,$45,$44
	.byte	$20,$41,$53,$20,$25,$30,$34,$58,$0D,$00

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

	.dbg	func, "main", "00", extern, "_main"

.segment	"CODE"

;
; printf("__CC65__ defined as %04x\n", __CC65__);
;
	.dbg	line, "checkversion.c", 32
	lda     #<(S0001)
	ldx     #>(S0001)
	jsr     pushax
	ldx     #$02
	lda     #$13
	jsr     pushax
	ldy     #$04
	jsr     _printf
;
; printf("compiler version is %u.%u\n", VER_MAJOR, VER_MINOR);
;
	.dbg	line, "checkversion.c", 33
	lda     #<(S0002)
	ldx     #>(S0002)
	jsr     pushax
	lda     #$02
	jsr     pusha0
	lda     #$13
	jsr     pusha0
	ldy     #$06
	jsr     _printf
;
; printf("__CC65__ is defined correctly as (VER_MAJOR * 0x100) + VER_MINOR\n");
;
	.dbg	line, "checkversion.c", 35
	lda     #<(S0003)
	ldx     #>(S0003)
	jsr     pushax
	ldy     #$02
	jsr     _printf
;
; return EXIT_SUCCESS;
;
	.dbg	line, "checkversion.c", 36
	ldx     #$00
	txa
	rts

	.dbg	line
.endproc

